### ISSUE TITLE
Workflow to clone Top 10 attacks to mirror site https://mltop10.info/

### ISSUE THREAD

**Issue by msnishanth9001** [OWASP/www-project-machine-learning-security-top-10#128]
Construct workflow to clone the Top 10 attack's MD File to the Repo https://github.com/mltop10-info/mltop10.info. 

So that all changes to attack scenarios are pushed by WF rather than human interaction.

**Comment by shsingh** [comment]
Hi @msnishanth9001 

commented on #129 

workflow for mirroring is at this stage less important then rendering of the markdown into pdf and epub.

**Comment by shsingh** [comment]
closing this issue for now. creating a workflow to mirror content will be done at later stage
