### ISSUE TITLE
chore(admin): assign owner(s) for ML02 Data Poisoning Attack

### ISSUE THREAD

**Issue by shsingh** [OWASP/www-project-machine-learning-security-top-10#164]
- [x] Assigned Lead Contributor for ML02
- [x] Update CODEOWNERS with contributor details

Ideally the Lead Contributor for ML02 will also be assigned to the cheatsheet - ref: #150

**Comment by yodap-dg** [comment]
Hi @shsingh, I can take the lead on this one. Thanks.

**Comment by shsingh** [comment]
ref: #183
