### ISSUE TITLE
chore(admin): assign owner(s) for ML07 Transfer Learning Attack

### ISSUE THREAD

**Issue by shsingh** [OWASP/www-project-machine-learning-security-top-10#169]
- [x] Assigned Lead Contributor for ML07
- [x] Update CODEOWNERS with contributor details

Ideally the Lead Contributor for ML07 will also be assigned to the cheatsheet - ref: #155

**Comment by techiemac** [comment]
Hey @shsingh I can take lead on this one

**Comment by shsingh** [comment]
ref: #184
