### ISSUE TITLE
add: Create a RELATED.md to list similar projects and SIGs

### ISSUE THREAD

**Issue by shsingh** [OWASP/www-project-machine-learning-security-top-10#29]
### Type

Website Issue Report

### What would you like to report?

This applies to both the website and documentation content.

- create a page which lists similar:
- OWASP projects
- other committees and SIGs (LF, OpenSSF, CSA) 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mik0w** [comment]
I've created a PR: https://github.com/OWASP/www-project-machine-learning-security-top-10/pull/31

**Comment by shsingh** [comment]
added: LEADER.md as a tab on website #33
