### ISSUE TITLE
fix: Website has incorrect pdf document 

### ISSUE THREAD

**Issue by sagarbhure** [OWASP/www-project-machine-learning-security-top-10#44]
### Type

Website Issue Report

### What would you like to report?

I would like to report the following issue/feedback
- Incorrect pdf downloaded from : https://owasp.org/www-project-machine-learning-security-top-10/2023/Acknowledgements.html

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msnishanth9001** [comment]
this should be solved with this issue? https://github.com/OWASP/www-project-machine-learning-security-top-10/issues/14

**Comment by shsingh** [comment]
oh nice pickup @msnishanth9001 leftovers from the template project directory. will fix this immediately.

**Comment by shsingh** [comment]
tracking this in #46 so closing this issue
