### ISSUE TITLE
[FEEDBACK]: Risk Ranking Reference

### ISSUE THREAD

**Issue by RAJANAGORI** [OWASP/www-project-machine-learning-security-top-10#56]
### Type

Documentation Issue Report

### What would you like to report?

Hi team,
I would like to focus on the missing information related to the Risk Ranking number of Top 10 at the starting of the page, the table mentioned in every vulnerability. 

It would be a great resource if added so that people can related to the risk associated with the vulnerability. 

@sagarbhure

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shsingh** [comment]
did you want to start working on #15 @RAJANAGORI ?

**Comment by RAJANAGORI** [comment]
@shsingh 
Sure, I will start working on this and raise the PR, but since I'm completely new to Machine learning concepts so I need to first understand the possible Likelihood and Impact based on the top 10 titles.

Although, I stated going through with the Risk Ranking guide shared by Sagar. soon come up with something useful :)

**Comment by shsingh** [comment]
did you want me to create an example say for one of the ML risks to get you started?

**Comment by RAJANAGORI** [comment]
Sure, it would be a good idea. Since, you already know about the dots of every information.

**Comment by shsingh** [comment]
tracking in https://github.com/OWASP/www-project-machine-learning-security-top-10/issues/15#issuecomment-1692428735
