### ISSUE TITLE
[FEEDBACK]: Rename 'Corrupted packages' to 'AI supply chain attacks'

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/www-project-machine-learning-security-top-10#85]
### Type

Suggestions for Improvement

### What would you like to report?

I believe 'Packages' to be a too specific term for the problem of supply chain attacks. Calling it 'supply chain attacks' will make the reader aware of the risk that any external component in the AI pipeline can be manipulated. 
Also, add 'data' as a potential supply chain risk, and refer to 'data poisoning' for that, and also add 'model', referring to the transfer learning attack.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aryanxk02** [comment]
Shall I take up this issue? @robvanderveer @shsingh

**Comment by shsingh** [comment]
created #105 for you @aryanxk02
